title: Stefano's Website
author:
  name: Stefano Santomaggio
  social links: =>
  email: stefano.santomaggio02@gmail.com
  github: ssantomaggio
description: > 
  Hello everyone I am a computer science student of UNIVAQ
show_excerpts: true 
minima:
  date_format: "%b %-d, %Y"  

markdown: kramdown
theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag
